[phases.setup]
nixPkgs = ["nodejs_20", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "npm install --production",
  "pip install python-telegram-bot==21.3 pyotp aiohttp aiofiles --break-system-packages"
]

[start]
cmd = "bash start.sh"